name: Build and Deploy

on:
  push:
    branches:
      - master
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '12'

      - name: Install npm packages
        run: npm install

      - name: Build assets
        run: npm run generate --fail-on-error

      - name: Get Time
        id: time
        uses: nanzm/get-time-action@v1.1
        with:
          timeZone: 8
          format: 'YYYYMMDDHHmmss'

      - uses: actions/upload-artifact@v2
        with:
          name: "${{ steps.time.outputs.time }}"
          path: dist/

      # - name: Deploy
      #   uses: fjogeleit/http-request-action@master
      #   with:
      #     url: "https://echo.cleaver.cloud/deploy/07-TJ3dYZGcXMps6JuezTUNm4gRcAWzIKKV5s6kLpfOIomxFP9dy6A"
      #     method: 'POST'
      #     timeout: 60000
